Update Build_7DR7299_immortalwrt_237_golang_msd_lite.yml

diff --git a/.github/workflows/Build_7DR7299_immortalwrt_237_golang_msd_lite.yml b/.github/workflows/Build_7DR7299_immortalwrt_237_golang_msd_lite.yml
--- a/.github/workflows/Build_7DR7299_immortalwrt_237_golang_msd_lite.yml
+++ b/.github/workflows/Build_7DR7299_immortalwrt_237_golang_msd_lite.yml
@@ -89,11 +89,11 @@ jobs:
         # ======== 编译下方插件，请先去掉注释 ======== 
         cd /builder/openwrt
 
-        # ======== 编译 OpenClash 最新版 =========
+        # ======== 编译 OpenClash 最新版（不推荐）=========
         # immortalwrt 插件库已经包含 OpenClash，若源码被删除或编译 OpenClash 最新版，使用以下命令自行编译，打开 immortalwrt官方插件库查询：https://github.com/immortalwrt/immortalwrt（选择 openwrt-24.10分支，打开 feeds.conf.default文件，再打开luci仓库找到“applications”查询插件）
         sed -i '1i src-git openclash https://github.com/vernesong/OpenClash.git;master' ./feeds.conf.default
         
-        # ======== 编译 passwall 最新版 =========
+        # ======== 编译 passwall 最新版（不推荐）=========
         # immortalwrt插件库已经包含 passwall，若源码被删除或编译 Passwall 最新版，使用以下命令自行编译，打开 immortalwrt官方插件库查询：https://github.com/immortalwrt/immortalwrt（选择 openwrt-24.10分支，打开 feeds.conf.default文件，再打开luci仓库找到“applications”查询插件）
         # 编译 passwall_luci，去掉下面注释，此命令会在 feeds.conf.default文件，第 1 行插入 passwall_luci
         sed -i '1i src-git passwall_luci https://github.com/Openwrt-Passwall/openwrt-passwall.git;main' ./feeds.conf.default
@@ -101,53 +101,54 @@ jobs:
         # 编译 passwall_packages，再次在 feeds.conf.default文件，第 1 行插入 passwall_packages (这样 packages 就变成了第 1 行，luci 变成了第 2 行)
         sed -i '1i src-git passwall_packages https://github.com/Openwrt-Passwall/openwrt-passwall-packages.git;main' ./feeds.conf.default
         
-        # ======== 编译 passwall2 最新版 =========
+        # ======== 编译 passwall2 最新版（不推荐）=========
         # 编译 passwall2_luci，不要和 passwall_luci 一起编译，编译出来的固件会不稳定，第 1 行插入 passwall2_luci
         #sed -i '1i src-git passwall2_luci https://github.com/Openwrt-Passwall/openwrt-passwall2.git;main' ./feeds.conf.default
         
     - name: Update feeds
       working-directory: /builder/openwrt
       run: |
-        ./scripts/feeds update -a
+        ./scripts/feeds update -a   
 
-       #=======编入第三方 msd_lite 插件，解决 IPTV 卡顿=======
+       #======= 解决 Passwall 的 Geoview 报错问题（置于更新和安装 feeds 命令之间）=======
+    - name: 升级 Passwall 工具链为 golang1.27
+      working-directory: /builder/openwrt
+      run: |
+        # 1. 直接将本地仓库根目录下的 golang1.27 复制到 feeds 目录
+        rm -rf feeds/packages/lang/golang1.27        
+        mkdir -p feeds/packages/lang/golang1.27
+        cp -rf "$GITHUB_WORKSPACE/golang1.27/." feeds/packages/lang/golang1.27/
+
+        # 2. 强制更新索引并安装 golang1.27（同时刷入 feeds 索引列表）
+        ./scripts/feeds update -f packages
+        ./scripts/feeds install -p packages -f golang1.27
+        
+        # 3. 删除临时目录
+        rm -rf tmp
+
+    - name: Install feeds
+      working-directory: /builder/openwrt
+      run: |
+        ./scripts/feeds install -a
+
+    - name: Install feeds
+      working-directory: /builder/openwrt
+      run: |
+        ./scripts/feeds install -a
+
+       #======= 编入第三方 msd_lite 插件，解决 IPTV 卡顿（使用 package 编译法，更新和安装 feeds 命令之后）=======
     - name: 编入第三方 msd_lite 插件
       working-directory: /builder/openwrt
       run: |
-        rm -rf  feeds/packages/net/msd_lite
-        rm -rf  feeds/luci/applications/luci-app-msd_lite
+        rm -rf feeds/packages/net/msd_lite
+        rm -rf feeds/luci/applications/luci-app-msd_lite
         git clone https://github.com/ximiTech/msd_lite.git package/msd_lite
-        git clone https://github.com/ximiTech/luci-app-msd_lite.git package/luci-app-msd_lite        
-
-       #=======解决 Passwall 的 Geoview 报错问题=======
-    - name: 强行升级 Golang 工具链
-      working-directory: /builder/openwrt
-      run: |
-        # 1. 彻底删除旧的 golang feed 目录
-        rm -rf feeds/packages/lang/golang
-    
-        # 2. 在 immortalwrt 官方的 master 主分支中把最新的 golang 源码克隆下来
-        git clone --depth=1 -b master https://github.com/immortalwrt/packages.git temp_packages
-    
-        # 3. 把新版 golang 复制回对应的 feeds 目录
-        mv temp_packages/lang/golang feeds/packages/lang/
-        rm -rf temp_packages
-    
-        # 4. 关键：重新生成 feeds 索引，确保新版 Go 被系统识别
-        ./scripts/feeds update -i
-        ./scripts/feeds install -f -p packages golang
-
-    - name: Install feeds
-      working-directory: /builder/openwrt
-      run: |
-        ./scripts/feeds install -a
-
-    - name: Install feeds
-      working-directory: /builder/openwrt
-      run: |
-        ./scripts/feeds install -a
-
-       # ======== 编译 OpenClash 最新版（使用 package 编译法）不推荐 =========
+        git clone https://github.com/ximiTech/luci-app-msd_lite.git package/luci-app-msd_lite
+        
+        # 删除临时目录
+        rm -rf tmp
+        
+       # ======== 1. 编译 OpenClash 最新版（使用 package 编译法）不推荐 =========
        # OpenClash 推荐使用上方写入 ./feeds.conf.default 编译法
        # immortalwrt 插件库已经包含 OpenClash，若源码被删除或编译 OpenClash 最新版，使用以下命令自行编译，打开 immortalwrt官方插件库查询：https://github.com/immortalwrt/immortalwrt（选择 openwrt-24.10分支，打开 feeds.conf.default文件，再打开luci仓库找到“applications”查询插件）
     #- name: Import Official Recommended OpenClash
@@ -165,6 +166,63 @@ jobs:
 
         # 删除临时目录
     #    rm -rf /tmp/OpenClash && rm -rf tmp
+
+       # ======== 2. 编译 Passwall 最新版（使用 package 编译法，更新和安装 feeds 命令之后）推荐 =========
+       # 不推荐使用写入 ./feeds.conf.default 编译法
+       # immortalwrt 插件库已经包含 Passwall ，若源码被删除或编译最新版，使用以下命令自行编译，打开 immortalwrt官方插件库查询：https://github.com/immortalwrt/immortalwrt（选择 openwrt-24.10分支，打开 feeds.conf.default文件，再打开luci仓库找到“applications”查询插件）
+    - name: Import Official Recommended Passwall
+      working-directory: /builder/openwrt
+      run: |
+        # 移除 openwrt feeds 自带的核心库
+        rm -rf feeds/packages/net/{xray-core,v2ray-geodata,sing-box,chinadns-ng,dns2socks,hysteria,ipt2socks,microsocks,naiveproxy,shadowsocks-rust,shadowsocksr-libev,simple-obfs,tcping,v2ray-plugin,xray-plugin,geoview,shadow-tls}
+        git clone https://github.com/Openwrt-Passwall/openwrt-passwall-packages package/passwall-packages
+
+        # 移除 openwrt feeds 过时的luci版本
+        rm -rf feeds/luci/applications/luci-app-passwall
+        git clone https://github.com/Openwrt-Passwall/openwrt-passwall package/passwall-luci
+
+        # 删除临时目录
+        rm -rf tmp
+
+       #======= 解决 Passwall 的 Geoview 报错问题，修改 passwall-packages 文件（安装 Passwall 之后）=======
+    - name: 修改 passwall-packages 目录下所有 Makefile 文件中 golang 路径指向 golang1.27
+      working-directory: /builder/openwrt
+      run: |
+        # 1. 修改 passwall-packages 目录下所有 Makefile 文件中 golang 路径指向 golang1.27
+        TARGET_DIRS=()
+        [ -d "package/dae" ] && TARGET_DIRS+=("package/dae")
+        [ -d "package/passwall-packages" ] && TARGET_DIRS+=("package/passwall-packages")
+
+        if [ ${#TARGET_DIRS[@]} -gt 0 ]; then
+          find "${TARGET_DIRS[@]}" -name "Makefile" -type f -exec sed -i \
+            -e 's|\<golang/golang-package.mk\>|golang1.27/golang-package.mk|g' \
+            -e 's|\<golang/host\>|golang1.27/host|g' {} +
+        else
+          echo "WARNING: 未找到 package/dae 或 package/passwall-packages 目录，忽略即可！"
+        fi
+
+        # 2. 检查是否成功替换 golang1.27 版本，如果退出，说明 golang 版本与 Passwall 要求的 golang 版本对不上。通过以下方法确认版本已经不一致，请打开 https://github.com/Openwrt-Passwall/openwrt-passwall-packages，打开 geoview/Makefile 文件，搜索“golang”并获取相关路径：/feeds/packages/lang/golang/golang-package.mk，确认能在本地仓库 golang1.27 目录下找到“golang-package.mk”文件，且路径一致，否则就是版本对不上（将 golang1.27 目录复制到 /feeds/packages/lang/ 目录下与 golang 并存）
+        echo "=== 检查是否成功替换 golang1.27 版本 ==="
+        GOLANG_TARGET_FILE="feeds/packages/lang/golang1.27/golang1.27/Makefile"
+        if [ -f "$GOLANG_TARGET_FILE" ] && grep -q "PKG_NAME:=golang1.27" "$GOLANG_TARGET_FILE"; then
+          echo "SUCCESS: 验证通过，$GOLANG_TARGET_FILE 包含 PKG_NAME:=golang1.27"
+        else
+          echo "ERROR: golang1.27 验证失败！未在 $GOLANG_TARGET_FILE 中找到 PKG_NAME:=golang1.27"
+          exit 1
+        fi
+
+        # 3. 检查修改结果（抽查核心组件 xray-core 的Makefile文件指向 golang1.27），检查失败会自动退出
+        echo "=== 检查 package/passwall-packages 下 所有的 Makefile 文件中的 Go 编译依赖指向 golang1.27 ==="
+        xray_Makefile="package/passwall-packages/xray-core/Makefile"
+        if [ -f "$xray_Makefile" ] && grep -q "golang1.27/golang-package.mk" "$xray_Makefile"; then
+          echo "SUCCESS: $xray_Makefile 中的 golang-package.mk 路径已成功修改为 golang1.27！"
+        else
+          echo "ERROR: $xray_Makefile 中的 golang-package.mk 路径替换失败！"
+          exit 1
+        fi
+
+        # 删除临时目录
+        rm -rf tmp
                 
     - name: Configuration Customization - Build_7DR7299_immortalwrt_237_golang_msd_lite 
       run: |
